config/routes.rb
Rails.application.routes.draw do

  get 'profesors/index'

  get 'profesors/show'

  get 'all_events/show' => 'all_events#show', :as => :all_events

  get 'single_event/new'

  get 'single_event/edit' => 'single_events#edit', :as => :edit_event

  get 'single_event/update'

  get 'single_event/index' => 'single_events#index', :as => :single_events

  get 'single_event/show' => 'single_events#show', :as => :event

  get 'mojegrupe/index' => 'mojegrupe#index', :as => :mojegrupe

  get 'mojegrupe/:id' => 'mojegrupe#show', :as => :grupa

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    authenticated :user do
      root :to => 'home#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end

    root :to => redirect('devise/sessions#new')

  get "users/sign_out" => redirect("devise/sessions#new")

  get "/podaci" => 'podaci#show', :as => :podaci

  get "/home" => 'home#show', :as => :home

  ActiveAdmin.routes(self)
  get 'popis/show'

  get 'pages/show'

  get 'home/show'

  resources :pages, only: [:show]
  resources :mojegrupe
  resources :profesors
  resources :uceniks
  resources :users

  resources :single_events do
    get :get_events, on: :collection
    get :get_all_events, on: :collection
  end

  end
end

app/models/single_event.rb
class SingleEvent < ActiveRecord::Base
	belongs_to :profesor
	belongs_to :group
	belongs_to :where
	belongs_to :event

	has_many :ucenik_events
	has_many :uceniks, through: :ucenik_events
end

app/controllers/single_events_controller.rb
class SingleEventsController < ApplicationController
respond_to :json
    helper_method :current_user
    before_filter :authenticate_user!

  

  def get_events #JSON zapis predavanja za kalendar(current_user)
    @event = current_user.profesor.events
    events = []
    @event.each do |event|
        @s_event = event.single_events
        @s_event.each do |s_event|

            @col = "#0066FF"
            @grupa
            @mjesto
            @adresa
            if s_event.group == nil
              @grupa = "";
            else
              @grupa = s_event.group.name
            end

            if event.where == nil
              @mjesto = ""
              @adresa = ""
            else
              @mjesto = s_event.where.name
              @adresa = s_event.where.adress
            end

            @ev = "<p><a href ='/single_event/show."+s_event.id.to_s+"'>Stranica predavanja</a></p>"

            if s_event.odrzano? && s_event.date <= Date.today.strftime("%Y-%m-%d")
              @col = "#00FF00"
            elsif !s_event.odrzano? && s_event.date < Date.today.strftime("%Y-%m-%d")
              @col = "#FF0000"
            elsif !s_event.odrzano? && s_event.date == Date.today.strftime("%Y-%m-%d")
              @col = "#FF9900"
            end




        events << {:id => s_event.id, :color => @col, :ev => @ev,:title => s_event.title, :start => s_event.date+" "+s_event.start,:end =>s_event.date+" "+s_event.end, :vrijeme => "<p><strong>"+s_event.start+" - "+s_event.end+"</strong></p>" ,:grupa => "<p><strong>Predavanje grupe:</strong></p> "+"<p>"+@grupa+"</p>", :mjesto => "<p><strong>Mjesto predavanja:</strong></p> "+"<p>"+@mjesto+"</p>", :adresa => "<p><strong>Adresa:</strong></p> "+"<p>"+@adresa+"</p>" }
    #  else 
       # events << {:id => event.id, :title => event.title, :start =>event.start_date.to_s+" "+event.start.to_s,:end =>event.start_date.to_s+" "+event.end.to_s , :vrijeme => "<p><strong>"+event.start+" - "+event.end+"</strong></p>" , :grupa => "<p><strong>Predavanje grupe:</strong></p> "+"<p>"+@grupa+"</p>", :mjesto => "<p><strong>Mjesto predavanja:</strong></p> "+"<p>"+@mjesto+"</p>", :adresa => "<p><strong>Adresa:</strong></p> "+"<p>"+@adresa+"</p>", :ranges => [{:start => "2000-1-1", :end => "3000-1-1"}] }
    #  end
    end
  end
    render :text => events.to_json
end


def get_all_events #JSON zapis predavanja za kalendar(svi user-i)
      @event = Event.all
    events = []
    @event.each do |event|
        @s_event = event.single_events
        @s_event.each do |s_event|

            @col = "#0066FF"
            @grupa
            @mjesto
            @adresa
            if s_event.group == nil
              @grupa = "";
            else
              @grupa = s_event.group.name
            end

            if event.where == nil
              @mjesto = ""
              @adresa = ""
            else
              @mjesto = s_event.where.name
              @adresa = s_event.where.adress
            end

            @ev = "<p><a href ='/single_event/show."+s_event.id.to_s+"'>Stranica predavanja</a></p>"

           # if s_event.odrzano? && s_event.date <= Date.today.strftime("%Y-%m-%d")
           #   @col = "#00FF00"
           # elsif !s_event.odrzano? && s_event.date < Date.today.strftime("%Y-%m-%d")
           #   @col = "#FF0000"
           # elsif !s_event.odrzano? && s_event.date == Date.today.strftime("%Y-%m-%d")
           #   @col = "#FF9900"
           # end

           if s_event.where.id == 1
            @col =  "#FF0000"
           elsif s_event.where.id == 2
            @col = "#00FF00"
           elsif s_event.where.id == 3
            @col = "#0000FF"
           elsif s_event.where.id == 4
            @col = "#FFCC00"
           elsif s_event.where.id == 5
            @col = "#00CCFF"
           elsif s_event.where.id == 6
            @col = "#C0C0C0"
           elsif s_event.where.id == 7
            @col = "#CC9900"
           elsif s_event.where.id == 8
            @col = "#FF00CC"
           elsif s_event.where.id == 9
            @col = "#000000"
           end

           @profesor = "<p><a href ='/profesors/show."+s_event.profesor.id.to_s+"'>"+s_event.profesor.name+"</a></p>"

        events << {:id => s_event.id, :profesor => "<p><strong>Profesor:</strong></p> "+"<p>"+@profesor+"</p>", :color => @col, :ev => @ev,:title => s_event.title, :start => s_event.date+" "+s_event.start,:end =>s_event.date+" "+s_event.end, :vrijeme => "<p><strong>"+s_event.start+" - "+s_event.end+"</strong></p>" ,:grupa => "<p><strong>Predavanje grupe:</strong></p> "+"<p>"+@grupa+"</p>", :mjesto => "<p><strong>Mjesto predavanja:</strong></p> "+"<p>"+@mjesto+"</p>", :adresa => "<p><strong>Adresa:</strong></p> "+"<p>"+@adresa+"</p>" }
    #  else 
       # events << {:id => event.id, :title => event.title, :start =>event.start_date.to_s+" "+event.start.to_s,:end =>event.start_date.to_s+" "+event.end.to_s , :vrijeme => "<p><strong>"+event.start+" - "+event.end+"</strong></p>" , :grupa => "<p><strong>Predavanje grupe:</strong></p> "+"<p>"+@grupa+"</p>", :mjesto => "<p><strong>Mjesto predavanja:</strong></p> "+"<p>"+@mjesto+"</p>", :adresa => "<p><strong>Adresa:</strong></p> "+"<p>"+@adresa+"</p>", :ranges => [{:start => "2000-1-1", :end => "3000-1-1"}] }
    #  end
    end
  end
    render :text => events.to_json
end


  def index
    if current_user
     @events = current_user.profesor.single_events    
     @user = current_user
<<<<<<< HEAD
     @event_grid = initialize_grid(@events, order: 'single_events.date',order_direction: 'asc')
=======

>>>>>>> 4a8a0996df53f3a2db426e0ad8538315fc9d0f55
    else
     redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
  end

  def show
    @event = SingleEvent.find(params[:format])
  end 

  def update
    @event = SingleEvent.find(params[:id])

    @event.update(event_params)

    flash[:notice] = 'Predavanje izmjenjeno'

    redirect_to event_path(params[:id])
  end

  def edit
    @event = SingleEvent.find(params[:format])
  end

  private
    def event_params
    params.require(:single_event).permit(:start, :end, :where, :date, :odrzano, ucenik_ids: [])
  end

    def press_params
      params.require(:ucenik_event).permit()
    end

end

app/helpers/single_event_helper.rb
module SingleEventHelper
end

app/views/single_events/edit.html.erb
<h2><%= @event.title %></h2>
<%= semantic_form_for @event do |f| %>
	<%= f.inputs do %>
		<div class="form-group">
		<%= f.input :start, :label => "Vrijeme početka:", :as => :time_picker  %>
		</div>

		<div class="form-group">
		<%= f.input :end, :label => "Vrijeme završetka:", :as => :time_picker%>
		</div>

		<div class="form-group">
		<%= f.input :where, :label => "Mjesto predavanja",  :as => :select%>
		</div>
		
		<div class="form-group">
		<%= f.input :date, :label => "Datum:", :as => :date_picker %>
		</div>
		
		<div class="form-group">
		<%= f.input :odrzano, :label => "Odrzano"%>
		</div>

		<p><h3>Popis učenika</h3></p>
		<div class="form-group">
		<%= f.input :uceniks, :label => "", :as => :check_boxes , :collection => Ucenik.includes(:groups).where(:groups => {:id => @event.group_id})%>

		</div>
	<% end %>
	<%= f.actions do %>
		<%= f.action :submit, :as => :button %>
      	<%= f.action :cancel, :as => :link %>
    <% end %>
<% end %>

app/views/single_events/index.html.erb
<<<<<<< HEAD

<%= grid(@event_grid) do |g| 

	g.column name: "ID", attribute: 'id' do |t|
		t.id
	end

	g.column name: "Naziv", attribute: 'title' do |t|
		t.title
	end

	g.column name: "Grupa" do |t|
		if t.group != nil
		link_to(t.group.name, grupa_path(t.id))
		else
			"Nema grupe"
		end
	end

	g.column name: "Datum predavanja", attribute: 'date',ordering: true do |t|
		t.date.to_date.strftime(" %d.%m.%Y.")
	end

	g.column name: "Početak predavanja", attribute: 'start' do |t|
		t.start
	end

	g.column name: "Kraj predavanja", attribute: 'end' do |t|
		t.end
	end

	g.column name: "Upisano predavanje", attribute: 'odrzano' do |t|
		t.odrzano? ? "Yes" : "No"
	end

	g.column do |t|
		link_to("Stranica predavanja", event_path(t.id))
	end

end -%>
=======
<h2>Moja predavanja</h2>
<% if @user != nil %>
<% if @events == nil %>
	<h2>Nema predavanja!</h2>
<% else %>
	<% @events.sort_by {|e| e.date}.each do |event| %>
		<ul>
			<li><td><%= event.date.to_date.strftime(" %d.%m.%Y.") %> <%= event.start+"-"+event.end %> <%= link_to event.title, event_path(event.id) %></li>
		</ul>
	<% end %>
<% end %>
<% end %>
>>>>>>> 4a8a0996df53f3a2db426e0ad8538315fc9d0f55

app/views/single_events/new.html.erb
<h1>SingleEvent#new</h1>
<p>Find me in app/views/single_event/new.html.erb</p>

app/views/single_events/show.html.erb
<h2><%=  @event.title %></h2>
<ul>
	<li><%= @event.start %></li>
	<li><%= @event.end %></li>
<<<<<<< HEAD
	<li><%= @event.date.to_date.strftime(" %d.%m.%Y.") %></li>
=======
	<li><%= @event.date %></li>
>>>>>>> 4a8a0996df53f3a2db426e0ad8538315fc9d0f55
</ul>
<h3>Prisutni učenici</h3>
<ul>
	<% @event.uceniks.each do |ucenik| %>
	<li><%= ucenik.name %></li>
	<% end %>	
</ul>
<p><%= link_to "Edit", edit_event_path(@event.id) %></p>

app/views/single_events/update.html.erb
<h1>SingleEvent#update</h1>
<p>Find me in app/views/single_event/update.html.erb</p>