config/routes.rb
Rails.application.routes.draw do

  get 'profesors/index'

  get 'profesors/show'

  get 'all_events/show' => 'all_events#show', :as => :all_events

  get 'single_event/new'

  get 'single_event/edit' => 'single_events#edit', :as => :edit_event

  get 'single_event/update'

  get 'single_event/index' => 'single_events#index', :as => :single_events

  get 'single_event/show' => 'single_events#show', :as => :event

  get 'mojegrupe/index' => 'mojegrupe#index', :as => :mojegrupe

  get 'mojegrupe/:id' => 'mojegrupe#show', :as => :grupa

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    authenticated :user do
      root :to => 'home#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end

    root :to => redirect('devise/sessions#new')

  get "users/sign_out" => redirect("devise/sessions#new")

  get "/podaci" => 'podaci#show', :as => :podaci

  get "/home" => 'home#show', :as => :home

  ActiveAdmin.routes(self)
  get 'popis/show'

  get 'pages/show'

  get 'home/show'

  resources :pages, only: [:show]
  resources :mojegrupe
  resources :profesors
  resources :uceniks
  resources :users

  resources :single_events do
    get :get_events, on: :collection
    get :get_all_events, on: :collection
  end

  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

        user ||= User.new # guest user
    if user.role == 'admin'
        can :manage, :all
    else
        can :read, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :events, through: :picked_days
	has_many :picked_days
end

app/models/event.rb
class Event < ActiveRecord::Base
	require 'date'

	belongs_to :profesor
	belongs_to :group
	has_many :days, through: :picked_days
	has_many :picked_days
	has_many :single_events
	belongs_to :where

	validates :start,:end,:start_date, presence: true


    after_create { |event|  #svako predavanje se pojedinačno zapisuje u bazu
    	@dani = Array.new(7)
    	@i = 0
    	@dani_count = 0
    	@br = 0
    	@zbr = 0

    if event.repeat?

    	@first_day = event.days.first.id
    	@d_c = @first_day

    		event.days.each do |day|
    			temp = day.id-@d_c
    			if temp < 0
    				temp = (day.id+7)-@d_c
    			end
    			date = event.start_date
    			@dani[@dani_count] = date+(temp)
    			@dani_count+=1
    		end

    	@br = event.br_pred/@dani_count-1
    	@i = @br

    	@dani_count-=1 	
    end


    while @i >= 0 && @dani_count >= 0
      s_event = SingleEvent.new
      s_event.event_id = event.id
      s_event.title = event.title
      s_event.start = event.start
      s_event.end = event.end

      if event.repeat?
      	s_event.date = @dani[@dani_count]+@zbr
  	  else
  	  	s_event.date = event.start_date
  	  end

      if event.profesor_id?
      	s_event.profesor_id = event.profesor_id
  	  end

  	  if event.where_id?
  	  	s_event.where_id = event.where_id
  	  end

  	  if event.group_id?
  	  	s_event.group_id = event.group_id
  	  end

      s_event.save
      @zbr+=7
      @i-=1

      if @i < 0 && @dani_count > 0
      	@dani_count-=1
      	@i = @br
      	@zbr = 0
      end
  end

    }

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :uceniks, through: :group_uceniks
	has_many :group_uceniks
	has_many :events
	belongs_to :profesor
end

app/models/group_ucenik.rb
class GroupUcenik < ActiveRecord::Base
	belongs_to :ucenik
	belongs_to :group
end

app/models/picked_day.rb
class PickedDay < ActiveRecord::Base
	belongs_to :event
	belongs_to :day
end

app/models/profesor.rb
class Profesor < ActiveRecord::Base
	has_one :user
	has_many :groups
	has_many :events
	has_many :single_events
	#validates_attachment_content_type :document, :content_type => ['application/pdf', 'application/msword', 'text/plain']
end

app/models/single_event.rb
class SingleEvent < ActiveRecord::Base
	belongs_to :profesor
	belongs_to :group
	belongs_to :where
	belongs_to :event

	has_many :ucenik_events
	has_many :uceniks, through: :ucenik_events
end

app/models/ucenik.rb
class Ucenik < ActiveRecord::Base
	has_many :groups, through: :group_uceniks
	has_many :group_uceniks

	has_many :ucenik_events
	has_many :single_events, through: :ucenik_events
end

app/models/ucenik_event.rb
class UcenikEvent < ActiveRecord::Base
	belongs_to :ucenik 
	belongs_to :single_event
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :profesor

	validates :profesor, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	def role?(r)
 	 role.include? r.to_s
	end


end

app/models/where.rb
class Where < ActiveRecord::Base
	has_many :events
	has_many :single_events
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mojegrupe_helper.rb
module MojegrupeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podaci_helper.rb
module PodaciHelper
end

app/helpers/popis_helper.rb
module PopisHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= params[:controller].parameterize %></a>
    </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>

      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <!-- login toolbar : -->
      <ul class="nav navbar-nav navbar-right">
      	<% if signed_in? %>
	      	<li><%= link_to current_user.email, edit_user_registration_path %></li>
	    	<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
	     	<li><%= link_to "Admin", admin_path %></li>
		<% else %>
    		<li><%= link_to "Sign in", new_user_session_path %></li>
		<% end %>
      </ul><!-- /.login toolbar -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_ucionice.html.erb
<% if params[:controller] == 'all_events' %>
<div class="well">
		<h2>Učionice</h2>
		<ul>
			<h3>Zagreb, Radnička cesta 27</h3>
			<li style="color:#FF0000">Njemačka</li>
			<li style="color:#00FF00">Engleska</li>
			<li style="color:#0000FF">Hrvatska</li>
			<h3>Zaprešić, Ante Starčevića 11</h3>
			<li style="color:#FFCC00">Frankfurt</li>
			<li style="color:#00CCFF">Paris</li>
			<li style="color:#C0C0C0">Munchen</li>
			<li style="color:#CC9900">Venecija</li>
			<li style="color:#FF00CC">London</li>
			<li style="color:#000000">Barcelona</li>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skola</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application','style','jquery-ui', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body id="<%= params[:controller].parameterize %>_controller" >
 
 <% if signed_in? %>  
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pavuna d.o.o.</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'home' ? 'active' : '' %>"><%= link_to "Home", home_path %></li>
            <li class="<%= params[:controller] == 'mojegrupe' ? 'active' : '' %>"><%= link_to "Moje Grupe", mojegrupe_path %></li>
             <li class="<%= params[:controller] == 'single_events' ? 'active' : '' %>"><%= link_to "Moja Predavanja", single_events_path %></li>
             <li class="<%= params[:controller] == 'all_events' ? 'active' : '' %>"><%= link_to "Sva Predavanja", all_events_path %></li>
          </ul>
                <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.email, podaci_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% if current_user.role == "admin" %>
          <li><%= link_to "Admin", admin_root_path %></li>
        <% end %>
      </ul><!-- /.login toolbar -->
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<% end %>
 <% if flash[:notice] %>
   <div class="alert alert-success"><%= flash[:notice] %></div>
 <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>Log-in</title>
    
    
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application','style', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
  </head>

<body>

    <div class="login-card">
    <h1>Log-in</h1><br>
    <%= yield %>
    
</div>    
    
  </body>
</html>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>